# Copyright 2020 The MathWorks, Inc.

name: Setup MATLAB
description: >-
  Set up MATLAB on a Linux-based GitHub-hosted runner
inputs:
  release:
    description: >-
      MATLAB release to set up (R2020a or later)
    required: false
    default: latest
  products:
    description: >-
      Array of products to install
    required: false
    default: |
      MATLAB
      Parallel_Computing_Toolbox
runs:
  using: node16
  main: dist/index.js
