# Copyright 2020 The MathWorks, Inc.

name: Setup MATLAB
description: >-
  Set up MATLAB on a Linux-based GitHub-hosted runner
inputs:
  release:
    description: >-
      MATLAB release to set up (R2020a or later)
    required: true
    default: latest
runs:
  using: node12
  main: dist/index.js
