# Copyright 2020-2025 The MathWorks, Inc.

name: Setup MATLAB
description: >-
  Set up a specific version of MATLAB
inputs:
  release:
    description: >-
      MATLAB release to set up (R2021a or later)
    required: false
    default: latest
  products:
    description: >-
      Products to set up in addition to MATLAB, specified as a list of product names separated by spaces
    required: false
    default: ""
  cache:
    description: >-
      Option to enable caching with GitHub Actions, specified as false or true
    required: false
    default: false
outputs:
  matlabroot:
    description: >-
      A full path to the folder where MATLAB is installed
runs:
  using: node20
  main: dist/setup/index.js
  post: dist/cache-save/index.js
  post-if: always()
