# Copyright 2020 The MathWorks, Inc.

name: Setup MATLAB
description: >-
  Set up MATLAB on a Linux-based GitHub-hosted runner
inputs:
  release:
    description: >-
      MATLAB release to set up (R2020a or later)
    required: false
    default: R2021b
  products:
    description: >-
      Array of products to install
    required: false
    default: MATLAB
  location:
    description: >-
      Destination location for MATLAB install
    required: false
    default: /opt/matlab

runs:
  using: node12
  main: dist/index.js
